name: Compile

on:
  pull_request:
    paths:
      - ".github/workflows/compile-fw.yml"
      - "ArduinoLoRaAPRSTracker.ino"

  push:
    paths:
      - ".github/workflows/compile-fw.yml"
      - "ArduinoLoRaAPRSTracker.ino"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:mkrwan1300
            platforms: |
              - name: arduino:samd


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          enable-deltas-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          libraries: |
            - source-path: ./
            - source-url: https://github.com/sandeepmistry/arduino-LoRa.git
            - source-url: https://github.com/107-systems/107-Arduino-NMEA-Parser.git

          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          sketch-paths: ./

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
